version: "3.8"

services:
    app-dev:
        build: .
        container_name: my-java-app
        ports:
            - "8080:8080"
            - "9090:9090"
        environment:
            - SPRING_PROFILES_ACTIVE=dev
        profiles:
            - dev
        command: ["mvn", "spring-boot:run"]
        develop:
            watch:
                - action: sync
                  path: ./src/
                  target: /app/src/
                - action: rebuild
                  path: pom.xml

    app-test:
        build: .
        container_name: my-java-app
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        profiles:
            - test
        command: ["mvn", "spring-boot:run"]
        develop:
            watch:
                - action: sync+exec
                  exec:
                      command: ["mvn", "test"]
                  path: ./src/
                  target: /app/src/
                - action: rebuild
                  path: pom.xml
    app-prod:
        build: .
        ports:
            - "8080:8080"
        profiles:
            - prod
        command:
            ["java", "-jar", "target/cloudmersive-interview-1.0-SNAPSHOT.jar"]
        environment:
            SPRING_PROFILES_ACTIVE: prod
