version: "3.8"

services:
    java-api:
        build: .
        container_name: my-java-app
        volumes:
            - ./:/app
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
        develop:
            watch:
                - action: sync
                  path: ./src/
                  target: /app/src/
                - action: rebuild
                  path: pom.xml
